runtime: php72

handlers:
  - url: /admin2
    static_dir: public/admin2

  - url: /css
    static_dir: public/css

  - url: /font
    static_dir: public/font

  - url: /front
    static_dir: public/front

  - url: /img
    static_dir: public/img

  - url: /storage/img/avatar
    static_dir: storage/app/public/img/avatar

  - url: /storage/img/xray
    static_dir: storage/app/public/img/xray

  - url: /storage
    static_dir: public/storage

  - url: /plugin
    static_dir: public/plugin

  - url: /header2
    static_dir: public/header2

  - url: /svg
    static_dir: public/svg

  - url: /js
    static_dir: public/js

env_variables:
  ## Put production environment variables here.
  TOOTH_IMG_DIR: img/toothImages/
  DB_CONNECTION: mysql
  DB_DATABASE: dental
  DB_USERNAME: mnkhod
  DB_PASSWORD: 981014
  DB_SOCKET: "/cloudsql/dental-285608:asia-east2:dental-db"
  APP_KEY: base64:yYt5/uLCMet3nFcgInwX7a8JrTEG6/QZgNQrOcpw5tY=
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  SESSION_DRIVER: cookie
  APP_ENV: prod
  GOOGLE_CLOUD_PROJECT_ID: dental-285608
  GOOGLE_CLOUD_KEY_FILE: null
  GOOGLE_CLOUD_STORAGE_BUCKET: dental-285608.appspot.com
  GOOGLE_CLOUD_ACCOUNT_TYPE: service_account
  GOOGLE_CLOUD_PRIVATE_KEY_ID: "0686fde22da4f0f8e13727b600abb37c41300753"
  GOOGLE_CLOUD_PRIVATE_KEY: "-----BEGIN PRIVATE KEY-----\nMIIEugIBADANBgkqhkiG9w0BAQEFAASCBKQwggSgAgEAAoIBAQCb+6V7abp6MaKu\nPvbADkUFmoL5Py4c0DFTBtGnnBphwwj+SBWfqNpJwhFKr/1jba6eaL9b8LnzmZAT\nivtiQLjWdw9MgZQ0Rj6Wx2wVq8PzMqmgyqiovdxm0cNE+BRI62PneCCIc9qIc2Gv\nOQ3gImkW1F8lntd0EtSAhIloIP75Defzi4h3D0W5g6JHeP2gQuXR6Qy4HGWw08Ag\nycOjScVnpGmL/IYgEb2+Td68j9vo675IqXlIz20T4p6lnqOt31eyeDvGuSqE5hJX\nXZco/VExO43Drq3wYtKQqIbeXRJ/0zkfeGNPBzCH97hYJij3A7uT24gYZmGKn6xr\nBb1IZW3zAgMBAAECgf8Is5dfqKT4GoOBYRmEipl3sEZXGGh2AXqJE0IMA7IfQdsI\niv1E7kXn5XOFd7vmvTT199fmL3KsZQjAYDUN+uTb0EGAiTO5W56b8XlGZa6qSnAk\n3/D3qPqfNhgLZvnJFACcuukNFVEIB8oi6iAso7KTlRK3OhK7bCT436OQK7PXwqN8\n3TxI86mvj2r/m75fcG6jdrMAFJRPPa/reqW6P2iLfsthSE+wYgupaLRnaXVx3taH\nwTkLMRHilxeP00SLOEhNcXZ9Bgj9VE2tM/f8xThi+0eKpfu8ujRXfGMu0PkayQGW\nSwHh6esnJy3UOFy23KFRUc69XpvIFWu7wpPf6hECgYEA2uRa1Er8Ptv157Bv4+Hi\n8UCn6+NzimE/Kho+0/yfj33znbyKnJzXd455Ekhj8G3QMihse9ipwyrS0W/xtByk\nSwjkWHMYB3d765seFbW2YnvefLTsEndJm/K6hn3CydBIkwGehE/TeQsfU3eXxi73\nb2oMETWlXn1MK6sfEi3wKNECgYEAtm0eCD9xzUojJMPRS+kn9FSrsZkdwYDI7QXP\n7OpHDmaIolM9Ky1yC0Ik5CvJKYuU4zWA9bYm0hRdOyee5Rq/tCq0pFRzfKVvVTQx\nzTtwcHNFG9fM66ze7Pi772++XpFoGrkqPTKylo0yu++2nfTx3y1J9RzfbNogEZKi\ngNOqm4MCgYBiIOUnLsaOV4WR7GL8whM/HEErWrg9XQM4GLP5zNKrPUetewyY0Sc3\nDcPxEkrbSh9/nOelTagtOlFwWsL8f6qXiND1ZgNrtYD0SoHeMawl0moXdfQvAxMY\numQsTsy4NIuUe7FYl4CyTu4oOQDtc7ixVdU7EdWk2n7/RKOVPsrfQQKBgEhXizJQ\nHov/W2Jn+Oa2hi6hKRkblC45KPS9elAEM7tlM8fTZI1rzy7hwwlsx7Ae9yMHA6Xs\n3wYuJy6fLqbB7cW/rbUA/G8wl67dLOarLJKbU4uQD2ZiPmEQ3k48LO0JkpQOW866\n/REw2y6mB/Apw4TyS8LU+VEMSu1NDf4ychSLAoGAf59gg0ZgNWdY5AIkLsAsusEu\ns0G3i0UqruSpbLF2Eu/ZeqnS1xAsIz5A6252U8IznWQXC4k7C8p+xsBaJHEZs3XH\npIrTVb4o5ZIPaVUC5lfpErD/XthYav7LJDaDXgz6GytSejEkaba676xsGC0jJ3Nl\nmURuhm/z/3xdvSU5nik=\n-----END PRIVATE KEY-----\n"
  GOOGLE_CLOUD_CLIENT_EMAIL: "dental-285608@appspot.gserviceaccount.com"
  GOOGLE_CLOUD_CLIENT_ID: 107176699227943327798
  GOOGLE_CLOUD_AUTH_URI: "https://accounts.google.com/o/oauth2/auth"
  GOOGLE_CLOUD_TOKEN_URI: "https://oauth2.googleapis.com/token"
  GOOGLE_CLOUD_AUTH_PROVIDER_CERT_URL: "https://www.googleapis.com/oauth2/v1/certs"
  GOOGLE_CLOUD_CLIENT_CERT_URL: "https://www.googleapis.com/robot/v1/metadata/x509/dental-285608%40appspot.gserviceaccount.com"
